repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.48.0
    hooks:
      # Creates Documentation based on Terraform Outputs and Variables
      # Requires Terraform-Docs (github.com/terraform-docs/terraform-docs)
      - id: terraform_docs
        args: [--args=--lockfile=false]
      # Check that code is formatted to `terraform fmt` canonical style
      - id: terraform_fmt
      # Lint code using `tflint` to ensure it matches the correct style
      - id: terraform_tflint
        args: [--args=--config=.tflint.hcl]
      # Runs `tfsec` to check for known security misconfigurations
      - id: terraform_tfsec
      # Runs `terraform validate` to check for valid Terraform code
      - id: terraform_validate

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: mixed-line-ending
      - id: trailing-whitespace
